from securitylib.passwords import *
from nose.tools import eq_, with_setup
from test_utils import setup_seeded_random, teardown_seeded_random, assert_raises_with_message


@with_setup(setup_seeded_random, teardown_seeded_random)
def test_generate_password():
    eq_(generate_password(), 'L&HDKb7m3&gE')
    eq_(generate_password(16), 'a14o*3e683H9i384')
    eq_(generate_password(12, False), 'CSZ^54*8FPUI')
    eq_(generate_password(12, True, False), 'm&cr*#y!hp4%')
    eq_(generate_password(12, True, True, False), 'ALwC#Xinfr%^')
    eq_(generate_password(12, True, True, True, False), 'I2SfXTuFUqjN')
    eq_(generate_password(50, True, True, True, True, False), '9@Vna73Q#E$p5Q^^RezXB4PUKwUU^z^5!KwpD9mND#A8Wz%sAW')
    eq_(generate_password(8), '!R4D@L#o')
    assert_raises_with_message(ValueError, 'Parameter length must be at least 8.', generate_password, 7)
    assert_raises_with_message(ValueError, 'At least one of upper, lower, digits or special must be True.', generate_password, 12, False, False, False, False)


def test_validate_password():
    eq_(validate_password(''), ['min_length', 'min_lower', 'min_upper', 'min_digits', 'min_special', 'min_strength'])
    eq_(validate_password('a'), ['min_length', 'min_upper', 'min_digits', 'min_special', 'min_strength'])
    eq_(validate_password('aaaaaa'), ['min_length', 'min_upper', 'min_digits', 'min_special', 'min_strength'])
    eq_(validate_password('aaaaaaaaaaaa'), ['min_upper', 'min_digits', 'min_special', 'min_strength'])
    eq_(validate_password('Aaaaaaaaaaaa'), ['min_digits', 'min_special', 'min_strength'])
    eq_(validate_password('A1aaaaaaaaaa'), ['min_special', 'min_strength'])
    eq_(validate_password('A1!aaaaaaaaa'), ['min_strength'])
    eq_(validate_password('A1!aaaaaaaaa', min_length=14), ['min_length', 'min_strength'])
    eq_(validate_password('A1!aaaaaaaaaaa', min_length=14), ['min_strength'])
    eq_(validate_password('A1!aaaaaaaaaaa', min_length=14, min_lower=5), ['min_strength'])
    eq_(validate_password('A1!aaaaaaaaaaa', min_length=14, min_lower=5, min_upper=3), ['min_upper', 'min_strength'])
    eq_(validate_password('AAA1!aaaaaaaaa', min_length=14, min_lower=5, min_upper=3), ['min_strength'])
    eq_(validate_password('AAA1!aaaaaaaaa', min_length=14, min_lower=5, min_upper=3, min_digits=4), ['min_digits', 'min_strength'])
    eq_(validate_password('AAA1111!aaaaaa', min_length=14, min_lower=5, min_upper=3, min_digits=4), [])
    eq_(validate_password('AAA1111!aaaaaa', min_length=14, min_lower=5, min_upper=3, min_digits=4, min_special=3), ['min_special'])
    eq_(validate_password('AAA1111!!!aaaa', min_length=14, min_lower=5, min_upper=3, min_digits=4, min_special=3), ['min_lower'])
    eq_(validate_password('AAA1111!!!aaaaa', min_length=14, min_lower=5, min_upper=3, min_digits=4, min_special=3), [])
    eq_(validate_password('5^yhx8xuutn5x9g', min_length=12, min_lower=1, min_upper=0), ['min_strength'])
    eq_(validate_password('#X9hTQ', min_length=6), ['min_strength'])
    eq_(validate_password('#X9hTQ', min_length=6, min_lower=1, min_upper=1, min_digits=1, min_special=1, min_strength=0), [])
    eq_(validate_password('7O81k2w6', min_length=8, min_lower=1, min_upper=1, min_digits=1, min_special=0), ['min_strength'])
    eq_(validate_password('$78jxATr', min_length=8), [])


def test_get_password_strength():
    eq_(get_password_strength(''), 0)
    eq_(get_password_strength('aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'), 2)
    eq_(get_password_strength('aaaabaaaaaaaaaabaaaaaaaaaaaaaaaaaaabaaaaaaaaaaaaaaaaaaaabaaaaaaaaaaaaaaaaaaaaabaaaaaaaa'), 58)
    eq_(get_password_strength('awL@hd5$c7cp'), 93)
    eq_(get_password_strength('Pac7#FC^'), 88)
    eq_(get_password_strength('cNxTHFgb#%e@'), 81)
    eq_(get_password_strength('3nYgj9JN'), 70)
    eq_(get_password_strength('pZm8uRk0HwBK'), 76)
    eq_(get_password_strength('nqgwxv9n93op'), 67)
    eq_(get_password_strength('4u%2U'), 58)
    eq_(get_password_strength('pacfwldj7wlx'), 60)

    eq_(get_password_strength('sYuj^gkCro*DBRj$'), 100)
    eq_(get_password_strength('ePMvy2*5u&z5'), 100)
    eq_(get_password_strength('x3m4@xukebowq3$d'), 100)
    eq_(get_password_strength('!$246YDtMSu'), 100)
    eq_(get_password_strength('aiCJvvjeQAWq!SKD'), 96)
    eq_(get_password_strength('QH8RbHEipy7bYoOY'), 96)
    eq_(get_password_strength('$v$yc1U5zLUF&%n'), 96)
    eq_(get_password_strength('^B8*75H%6$YXAE*'), 94)
    eq_(get_password_strength('LI@S9Fnu1a*in'), 94)
    eq_(get_password_strength('9rom6seypl03ficn'), 94)
    eq_(get_password_strength('!$HAltUxLF0'), 93)
    eq_(get_password_strength('1%QZYDO6#8XNQ'), 91)
    eq_(get_password_strength('*b&^b&s@ytiv%b&@'), 87)
    eq_(get_password_strength('CgvqM3$gDZ3rQX'), 87)
    eq_(get_password_strength('7g6XcyCFBd89Fq'), 85)
    eq_(get_password_strength('b5mF4x%lHu'), 84)
    eq_(get_password_strength('B&U323$2'), 82)
    eq_(get_password_strength('CO1W!$TT@^$JA'), 82)
    eq_(get_password_strength('@egx9^s3%3^9'), 81)
    eq_(get_password_strength('$78jxATr'), 81)
    eq_(get_password_strength('77746@17$5*39@9'), 81)
    eq_(get_password_strength('heZ4SjLPH7MhCXc'), 79)
    eq_(get_password_strength('^521@5*8!^6'), 79)
    eq_(get_password_strength('b74dg9AE'), 78)
    eq_(get_password_strength('7O81k2w6'), 78)
    eq_(get_password_strength('5^yhx8xuutn5x9g'), 76)
    eq_(get_password_strength('BN3NH1A5WGLEKN'), 76)
    eq_(get_password_strength('AB!OZ^LMWVMC@'), 76)
    eq_(get_password_strength('0#4^7272'), 75)
    eq_(get_password_strength('rga67YHtbbfq'), 75)
    eq_(get_password_strength('7!4@^%ju!b'), 73)
    eq_(get_password_strength('4CS2HWL7ES23W'), 73)
    eq_(get_password_strength('YLr^sDGrzwkKKn'), 73)
    eq_(get_password_strength('YT#I$KEDX'), 72)
    eq_(get_password_strength('*NF$@^J$GB^'), 72)
    eq_(get_password_strength('juduMB2OV1'), 72)
    eq_(get_password_strength('TI%JKU#JR#Y'), 72)
    eq_(get_password_strength('F!CBM&W!GV'), 72)
    eq_(get_password_strength('3USDG501'), 70)
    eq_(get_password_strength('SqEZ0nvb'), 70)
    eq_(get_password_strength('OY%BUPZ^'), 70)
    eq_(get_password_strength('V49WL458ZV'), 70)
    eq_(get_password_strength('&NFE#!PEO'), 70)
    eq_(get_password_strength('$x!trx!j%j#xdb^'), 69)
    eq_(get_password_strength('*@7w^%*@'), 69)
    eq_(get_password_strength('dIJwYEYlJkMUXzV'), 67)
    eq_(get_password_strength('wzkfDUssqCxmefK'), 67)
    eq_(get_password_strength('h%hq@jrdsg'), 66)
    eq_(get_password_strength('KFWS@YRVY'), 63)
    eq_(get_password_strength('QMR7UWMKO'), 63)
    eq_(get_password_strength('%#^#!*&$@**^^%&'), 63)
    eq_(get_password_strength('R4XUSL9I'), 63)
    eq_(get_password_strength('ox90ZV^'), 61)
    eq_(get_password_strength('81661417624564'), 61)
    eq_(get_password_strength('IxsHOSRIjV'), 61)
    eq_(get_password_strength('8r&O2JR'), 61)
    eq_(get_password_strength('^%$%@##!@^*^##'), 61)
    eq_(get_password_strength('%&^*%!%%!&@^**'), 60)
    eq_(get_password_strength('#X9hTQ'), 60)
    eq_(get_password_strength('tXqxNpJa'), 60)
    eq_(get_password_strength('vxu6r0kmyg'), 60)
    eq_(get_password_strength('*@%^*^!$$$%$%'), 60)
    eq_(get_password_strength('RQYSSJJMQDLEB'), 58)
    eq_(get_password_strength('6^987#%'), 58)
    eq_(get_password_strength('5%4$32'), 57)
    eq_(get_password_strength('0*!UY'), 55)
    eq_(get_password_strength('ayjnngzzwtfbsx'), 55)
    eq_(get_password_strength('DFBBTHCBTO'), 54)
    eq_(get_password_strength('VYYFDLPCLF'), 54)
    eq_(get_password_strength('Mv&4'), 51)
    eq_(get_password_strength('2k&5%m'), 51)
    eq_(get_password_strength('6#hp&c'), 51)
    eq_(get_password_strength('E%#VD'), 48)
    eq_(get_password_strength('yzg@!x'), 43)
    eq_(get_password_strength('2495839'), 42)
    eq_(get_password_strength('0%$&'), 40)
    eq_(get_password_strength('oEmpYSR'), 40)
    eq_(get_password_strength('xELCgY'), 39)
    eq_(get_password_strength('%9QQ'), 39)
    eq_(get_password_strength('Z9l'), 36)
    eq_(get_password_strength('1H*'), 36)
    eq_(get_password_strength('K4z'), 36)
    eq_(get_password_strength('0s^p'), 34)
    eq_(get_password_strength('fv@gk'), 34)
    eq_(get_password_strength('X!MJ'), 33)
    eq_(get_password_strength('#Ii'), 33)
    eq_(get_password_strength('IF9R'), 33)
    eq_(get_password_strength('!9m'), 30)
    eq_(get_password_strength('%1i'), 30)
    eq_(get_password_strength('*u6'), 30)
    eq_(get_password_strength('j$!'), 30)
    eq_(get_password_strength('$$&'), 27)
    eq_(get_password_strength('k@zo'), 27)
    eq_(get_password_strength('cgP'), 25)
    eq_(get_password_strength('D^'), 24)
    eq_(get_password_strength('6Y'), 24)
    eq_(get_password_strength('%L'), 24)
    eq_(get_password_strength('90d'), 22)
    eq_(get_password_strength('7p'), 18)
    eq_(get_password_strength('1p'), 18)
